# Actividades - HHCC

1.- Descargar el archivo csv compartido e importalo en una hoja de cálculo de Google, donde lo analizarás de forma global, para luego realizar análisis más específicos y crear visualizaciones simples para los datos.
2. Revisión, adecuación y limpieza de csv: 
    + Crear una planilla de cálculo en Google Sheets y nombrarla **<font color='red'>set_total</font>**. Nombrar **<font color='red'>Data</font>**. a la hoja principal de la planilla. 
    + Buscar registros duplicados y eliminarlos.
    + Chequear el formato de los datos (numérico en las columnas en que deba haber números, texto en las columnas correspondientes, etc.)
    + Separar la columna "duration" en dos: en "duration" deben quedar solo los números, mientras que la que quede con los textos deben llamarla "tiempo_temporadas".
    + Crear una columna a la izquierda de la columna "title_oscar" y titularla "género". Indicar "Femenino" o "Masculino" en los registros que tienen como categorias ACTOR, ACTOR IN A LEADING ROLE, ACTOR IN A SUPPORTING ROLE, ACTRESS, ACTRESS IN A LEADING ROLE, ACTRESS IN A SUPPORTING ROLE, según corresponda. (Dejar vacía si no se corresponde las categorias mencionadas).
    + Crear una columna que se complete con un valor en función de la relación entre taquilla (box_office_x_millon) y presupuesto (budget_x_million) de las películas.
        si es menor o igual a 1:  `Fracaso`
        si es menor o igual a 5: `Regular`
        si es menor o igual a 15: `Buena`
        si es menor o igual a 25: `Éxito`
        si es menor o igual a 50: `Éxitazo`
        si es mayor a 50: `Genios Totales`

3. Realizar cada una de las siguientes consignas en una hoja de la planilla **<font color='red'>set_total</font>**, nombrando cada hoja según la consigna indique. Titular los gráficos de manera adecuada y agregar las etiquetas de los datos y leyendas, 

    <b>A.</b> Realizar un gráfico (hoja **Gráfico 1**) que muestre la relación entre la cantidad de series y películas disponibles en Netflix.

    <b>B.</b> Construir una tabla dinámica (hoja **Tabla dinámica 1**) que muestre de manera descendente los 15 países que tienen mayor cantidad total de títulos en la plataforma, desglosando por tipo de contenido.

    <b>C.</b> Realizar un gráfico (hoja **Gráfico 2**) a partir de la tabla dinámica del punto anterior, mostrando la información sólo para los primeros 10 países (mostrar el desglose por tipo de contenido).

    <b>D.</b> Construir una tabla dinámica (hoja **Tabla dinámica 2**) que muestre el nombre de las películas nominadas, el año de la ceremonia correspondiente y la cantidad de oscar ganados (Winner = 1). Agregar una métrica/valor calculado para mostrar la relación entre nominaciones y estatuillas ganadas, utilizando para ello la formula  `=CONTAR.SI(winner;"=1")/CONTARA(winner)` (establecer la opción "Personalizado" para la Configuración "Sumar por"). Dejar la tabla dinámica organizada de mayor a menor por esta columna calculada. 

    <b>E.</b> Crear una tabla (hoja **Tabla 1**) para mostrar los datos de la tabla dinámica del punto anterior, limitada sólo a las 4 películas de mejor perfomance en los oscar.
    
    <b>F.</b> Contruir una tabla dinámica (hoja **Tabla dinámica 3**)  que muestre la cantidad total de títulos estrenados por año, mostrando también cuántos son películas y cuántas series. Ordenar cronológicamente, comenzando por el más actual.

### Informe set_total - Enlace a <a href="https://docs.google.com/spreadsheets/d/1YG1MyoP8GbrTIiJ_s6pWZL1517XSL8dJ0SejZrh5RNw/edit?usp=sharing">set total</a> modificado

<p>En la base de datos analizada se encontraron (y eliminaron) 2 registros duplicados, entendiendo por estos aquellos que eran idénticos en todos los campos. </p>

<p>En algunos campos numéricos, los valores fueron tomados como fechas o como texto, principalmente debido a como el programa consideraba el punto("."); lo solucioné duplicando los datos y reemplazando el punto por una coma. Esto ocurrió en los siguientes campos: <i>imdb_score</i>, <i>budget_x_million</i> y <i>box_office_x_million</i>.</p>

##### Para la creación de columna **Género** utilice la siguiente fórmula: 

<p><i>    =ARRAYFORMULA(SI(REGEXMATCH($P2;"ACTOR|ACTOR IN A LEADING ROLE|ACTOR IN A SUPPORTING ROLE");"Masculino"; SI(REGEXMATCH($P2;"ACTRESS|ACTRESS IN A LEADING ROLE|ACTRESS IN A SUPPORTING ROLE");"Femenino";""))))</i></p>

##### Para la columna que analiza la relación entre **taquilla y presupuesto** utilicé la siguiente fórmula:
<p><i>    =ARRAYFORMULA(SI.ERROR(SI($W2/$V2<=1;"Fracaso";SI($W2/$V2<=5;"Regular";SI($W2/$V2<=15;"Buena";SI($W2/$V2<=25;"Exito";SI($W2/$V2<=50;"Exitazo";SI($W2/$V2>50;"Genios totales";""))))));""))</i></p>

##### En ambos casos corroboré visualmente que funcionaban correctamente.

<img src="/work/Imagenes/deepnote 2.jpg">

**Gráfico 1** (Punto 3-a)
<p>En este gráfico observamos que en el contendio de Netflix predominan las peliculas con un 70% del total de su contenido</p>
<iframe title="Embedded cell output" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRk5mIbq0xLRIFOIz-KqeggW-gMnT0c3DLQi1SPd-hGBe1fc1iT7f4DD0rQz8PoMpD_9pH4Qn7wLpT0/pubchart?oid=137380759&format=image" height="400" width="700"></iframe>

**Tabla dinámica 1** (Punto 3-b)
<p>Esta tabla muestra los 15 países que tienen mayor cantidad de contenido en la plataforma, con una clara predominancia de títulos estadounidenses, en su mayoría peliculas.</p>
<img src="/work/Imagenes/3b.jpg">

**Gráfico 2** (Punto 3-c)
En este gráfico se observan los 10 países con mayor contendio en la plataforma, apreciandose mejor la predominancia de títulos estadounidenses.</p>
<iframe title="Embedded cell output" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vRk5mIbq0xLRIFOIz-KqeggW-gMnT0c3DLQi1SPd-hGBe1fc1iT7f4DD0rQz8PoMpD_9pH4Qn7wLpT0/pubchart?oid=1419318574&format=image" height="600" width="900"></iframe>

**Tabla dinámica 2** (Punto 3-d)
<p>En esta tabla podemos observar que la relación premios/nominaciones no es una métrica adecuada ya que da lo mismo si el título ganó 1 o 10 premios. Por ejemplo, una película que ganó un solo premio con una sola nominación se ubica más arriba de una que ganó 5 y tuvo 6 nominaciones.</p>
<img src="/work/Imagenes/3d.jpg">

**Tabla 1** (Punto 3-e)
<p>Lo mismo que la tabla anterior, denota que la métrica no es adecuada porque en teoría las 4 peliculas con mejor performance solo tuvieron una nominación y un premio.</p>
<img src="/work/Imagenes/3e.jpg">

**Tabla dinámica 3** (Punto 3-f)
<p>Nada relevante que acotar; la mayoría de los títulos son de los últimos 10 años.</p>
<img src="/work/Imagenes/3f.jpg">

# Actividades - Python

  Desarrolar el código en python que permita realizar las siguientes instrucciones.
*   Use las estrategías de consulta apropiadas para:  
    <b>i</b> Buscar registros duplicados y eliminarlos. 
    
    <b>ii</b> Chequear el formato de los datos (numérico en las columnas en que deba haber números, texto en las columnas correspondientes, etc.). 
    
    <b>iii</b> Separar la columna "duration" en dos: en "duration" deben quedar solo los números, mientras que la que quede con los textos deben llamarla "tiempo_temporadas".
    
    <b>vi.</b> Construir un DF  que muestre de manera descendente los 15 países que tienen mayor cantidad total de títulos en la plataforma, desglosando por tipo de contenido.
    
    <b>v.</b> Mostrar las películas clasificadas como **drama** por netflix, que hayan ganado el Oscar entre 2010 y 2020 y que estén en esta plataforma. 
    
    <b>vi.</b> Construir un DF que muestre el nombre de las películas nominadas, el año de la ceremonia correspondiente, la cantidad de nominaciones y la cantidad de oscar ganados. Agregar una columna que sea el resultado de calcular la relación entre estatuillas ganadas y nominaciones totales. Organizar la tabla con mayor o igual a 10 nominaciones y de mayor a menor por esa de la relación calculada, limitada sólo a las 20 películas de mejor perfomance en los oscar.

In [24]:
import pandas as pd
from IPython.display import display

# i

print("Respuesta i - \'Buscar registros duplicados y eliminarlos\':")
#Abro el archivo como un Dataframe
set_total = pd.read_csv('/work/Data/set_total .csv')
# Verifico la cantidad de registros duplicados
print('Hay', set_total.duplicated().sum(), 'registros duplicados')
print(set_total.shape)
# Elimino registros duplicados
set_total.drop_duplicates(inplace=True)
# Verifico que se hayan eliminado
print(set_total.shape)
print()

# ii

print("Respuesta ii - \'Chequear el formato de los datos\':")
print(f'Información de los tipos de datos de set_total: ')
# Reviso los tipos de datos
print(set_total.dtypes)
print()

# Creo una función que me permita cambiar los tipos de datos
def cambio_type(df, lista, tipo):
    for columna_nombre in lista:
        if tipo == 'int' or tipo == 'float' :
            df[columna_nombre].fillna(0, inplace=True)
        df[columna_nombre] = df[columna_nombre].astype(tipo)
    return df

# Convierto las siguientes columnas a int
lista1 = ['id_content', 'release_year', 'year_ceremony', 'winner']
cambio_type(set_total, lista1, 'int')

# Covierto las siguientes columnas a str
lista2=['title_content', 'cast', 'director', 'country', 'listed_in', 'language', 'title_oscar', 'category', 'name', 'directed_by', 'starring']
cambio_type(set_total, lista2, 'string')

# Covierto las siguientes columnas a category
lista3=['type', 'rating']
cambio_type(set_total, lista3, 'category')

print('Se reemplazaron los valores nulos por cero, y se adecuaron los tipos de datos')
print(f'Información de los tipos de datos de set_total con las modificaciones: ')
print()
print(set_total.dtypes)
print()

# iii

print("Respuesta iii - \'Separar la columna duration en dos\':")
# Realizo un split para separar los datos en dos columnas
set_total[['duration', 'tiempo_temporadas']] = set_total['duration'].str.split(' ', 1, expand=True)
print(set_total[['duration', 'tiempo_temporadas']].head(10))
print()

# iv

print("Respuesta iv - \'Construir un DF  que muestre de manera descendente los 15 países que tienen mayor cantidad total de títulos en la plataforma, desglosando por tipo de contenido\':")
print()
# Separo las columnas necesarias en un nuevo df
df_iv = set_total[[ 'id_content','country','type']]
# Elimino datos nulos
df_iv = df_iv.dropna()
# Elimno datos con coma en la columna country, para evitar contar las colaboraciones
df_iv = df_iv.loc[~df_iv['country'].str.contains(',') ]
# Realizo un groupby con country y type que muestre la cantidad de contenido por país y tipo de contenido
df_iv = df_iv.groupby(['country','type']).count().sort_values(['id_content','country'], ascending=False)

display(df_iv.head(15))
print()

# v

print("Respuesta v - \'Mostrar las películas clasificadas como drama por netflix, que hayan ganado el Oscar entre 2010 y 2020 y que estén en esta plataforma.\':")
print()
# Preparo un df con las columnas y limitaciones necesarias
df_v = set_total.loc[(set_total['listed_in'].str.contains('Drama')) 
                      & (set_total['winner']==1) 
                      & (set_total['year_ceremony']>= 2010) 
                      & (set_total['year_ceremony']<=2020)]
display(df_v.head(5))

# vi

print("Respuesta vi - \'Construir un DF que muestre el nombre de las películas nominadas, el año de la ceremonia correspondiente, la cantidad de nominaciones y la cantidad de oscar ganados. Agregar una columna que sea el resultado de calcular la relación entre estatuillas ganadas y nominaciones totales. Organizar la tabla con mayor o igual a 10 nominaciones y de mayor a menor por esa de la relación calculada, limitada sólo a las 20 películas de mejor perfomance en los oscar.\':")
print()

# Creo un df con las columnas que necesito
df_vi = set_total[['title_oscar','year_ceremony','winner']].reset_index(drop= True)
# Hago un groupby con la cantidad de nomicaciones
df_vi_nom = df_vi.groupby(['title_oscar','year_ceremony']).count()
# Hago un groupby con la cantidad de premios
df_vi_win = df_vi.groupby(['title_oscar','year_ceremony']).sum('winner')
# Nombro de manera más adecuadas las columnas correspondientes
df_vi_nom.columns = ['Nominaciones']
df_vi_win.columns = ['Oscars ganados']
# Combino ambos agrupamientos en el df final
df_vi_final = pd.merge(df_vi_nom, df_vi_win, on=['title_oscar','year_ceremony'], how='inner')
# Agrego la columna de ratio entre oscar ganados y nominaciones
df_vi_final['Ratio'] = (df_vi_final['Oscars ganados'] / df_vi_final['Nominaciones']).round(2)
# Aparecerán solo las películas con más de 10 nominaciones
df_vi_final = df_vi_final[df_vi_final['Nominaciones']>=10]
# Ordeno las peliculas por ratio en orden descendente
df_vi_final.sort_values(by='Ratio', ascending=False, inplace=True)
# Limito a las primeras 20 peliculas por ratio
display(df_vi_final.head(20))

Respuesta i - 'Buscar registros duplicados y eliminarlos':
Hay 2 registros duplicados
(11427, 23)
(11425, 23)

Respuesta ii - 'Chequear el formato de los datos':
Información de los tipos de datos de set_total:
id_content              float64
type                     object
title_content            object
release_year            float64
cast                     object
director                 object
country                  object
rating                   object
duration                 object
listed_in                object
runtime                 float64
imdb_score              float64
language                 object
title_oscar              object
category                 object
name                     object
year_ceremony           float64
winner                  float64
directed_by              object
starring                 object
budget_x_million        float64
box_office_x_million    float64
imdb                    float64
dtype: object

Se reemplazaron los valores nulos por cero, y se adecuaron los tipos de datos
Información de los tipos de datos de set_total con las modificaciones:

id_content                 int64
type                    category
title_content             string
release_year               int64
cast                      string
director                  string
country                   string
rating                  category
duration                  object
listed_in                 string
runtime                  float64
imdb_score               float64
language                  string
title_oscar               string
category                  string
name                      string
year_ceremony              int64
winner                     int64
directed_by               string
starring                  string
budget_x_million         float64
box_office_x_million     float64
imdb                     float64
dtype: object

Respuesta iii - 'Separar la columna duration en dos':
  duration tiempo_temporadas
0       90               min
1        2           Seasons
2        1            Season
3        1            Season
4        2           Seasons
5        1            Season
6       91               min
7      125               min
8        9           Seasons
9      104               min

Respuesta iv - 'Construir un DF  que muestre de manera descendente los 15 países que tienen mayor cantidad total de títulos en la plataforma, desglosando por tipo de contenido':

                        id_content
country        type
United States  Movie          2197
India          Movie           892
United States  TV Show         756
United Kingdom TV Show         213
               Movie           207
Japan          TV Show         169
South Korea    TV Show         159
Canada         Movie           122
Spain          Movie            97
Egypt          Movie            92
Nigeria        Movie            84
Indonesia      Movie            77
Turkey         Movie            76
Japan          Movie            76
India          TV Show          76

Respuesta v - 'Mostrar las películas clasificadas como drama por netflix, que hayan ganado el Oscar entre 2010 y 2020 y que estén en esta plataforma.':

,id_content,type,title_content,release_year,cast,director,country,rating,duration,listed_in,...,category,name,year_ceremony,winner,directed_by,starring,budget_x_million,box_office_x_million,imdb,tiempo_temporadas
417,393,Movie,Django Unchained,2012,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",Quentin Tarantino,United States,R,165,"Action & Adventure, Dramas",...,ACTOR IN A SUPPORTING ROLE,Christoph Waltz,2013,1,Quentin Tarantino,['Jamie Foxx'. 'Christoph Waltz'. 'Leonardo Di...,100.0,425.4,8.4,min
421,393,Movie,Django Unchained,2012,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",Quentin Tarantino,United States,R,165,"Action & Adventure, Dramas",...,WRITING (Original Screenplay),Written by Quentin Tarantino,2013,1,Quentin Tarantino,['Jamie Foxx'. 'Christoph Waltz'. 'Leonardo Di...,100.0,425.4,8.4,min
750,703,Movie,Silver Linings Playbook,2012,"Bradley Cooper, Jennifer Lawrence, Robert De N...",David O. Russell,United States,R,122,"Comedies, Dramas, Independent Movies",...,ACTRESS IN A LEADING ROLE,Jennifer Lawrence,2013,1,David O. Russell,['Bradley Cooper'. 'Jennifer Lawrence'. 'Rober...,21.0,236.4,7.7,min
2195,2121,Movie,Les Misérables,2012,"Hugh Jackman, Russell Crowe, Anne Hathaway, Am...",Tom Hooper,"United Kingdom, United States",PG-13,158,"Dramas, International Movies, Music & Musicals",...,ACTRESS IN A SUPPORTING ROLE,Anne Hathaway,2013,1,Tom Hooper,['Hugh Jackman'. 'Russell Crowe'. 'Anne Hathaw...,61.0,441.8,7.6,min
2197,2121,Movie,Les Misérables,2012,"Hugh Jackman, Russell Crowe, Anne Hathaway, Am...",Tom Hooper,"United Kingdom, United States",PG-13,158,"Dramas, International Movies, Music & Musicals",...,MAKEUP AND HAIRSTYLING,Lisa Westcott and Julie Dartnell,2013,1,Tom Hooper,['Hugh Jackman'. 'Russell Crowe'. 'Anne Hathaw...,61.0,441.8,7.6,min

Respuesta vi - 'Construir un DF que muestre el nombre de las películas nominadas, el año de la ceremonia correspondiente, la cantidad de nominaciones y la cantidad de oscar ganados. Agregar una columna que sea el resultado de calcular la relación entre estatuillas ganadas y nominaciones totales. Organizar la tabla con mayor o igual a 10 nominaciones y de mayor a menor por esa de la relación calculada, limitada sólo a las 20 películas de mejor perfomance en los oscar.':

,,Nominaciones,Oscars ganados,Ratio
title_oscar,year_ceremony,,,
The Lord of the Rings: The Return of the King,2004,11,11,1.00
Cabaret,1973,10,8,0.80
Slumdog Millionaire,2009,10,8,0.80
Titanic,1998,14,11,0.79
The English Patient,1997,12,9,0.75
Amadeus,1985,11,8,0.73
Gandhi,1983,11,8,0.73
The Sting,1974,10,7,0.70
Ma Rainey's Black Bottom,1971,10,7,0.70
Gravity,2014,10,7,0.70
Dear Basketball,1986,11,7,0.64
From Here to Eternity,1954,13,8,0.62
Star Wars,1978,10,6,0.60
Mad Max: Fury Road,2016,10,6,0.60
Dances with Wolves,1991,12,7,0.58
The Godfather Part II,1975,11,6,0.55
Shakespeare in Love,1999,13,7,0.54
The Artist,2012,10,5,0.50
The Hateful Eight,1961,10,5,0.50
Zootopia,1966,10,5,0.50

# Actividades - Looker Studio

####  Crear un informe de visualización desde Looker Studio

1. Conectar la hoja **<font color='red'>Data</font>** del archivo **<font color='red'>set_total</font>**  a Looker Studio: 
    * Recordá que podés darle estilo y diseño para hacerlo más vistoso, llamativo y organizado.
    * Analizá las consignas para que los datos que conectes sean suficientes

2. Revisar que los datos se correspondan con el tipo de dato adecuado según las definiciones propias de Looker Studio (Fechas, Texto, Año, País, Porcentaje, Duración, Ciudad, etc.) Modificar el tipo de dato si corresponde.

3. Realizar las siguientes consignas, teniendo en cuenta los datos, las etiquetas, leyendas y títulos según sea posible. Acomodá las visualizaciones como consideres conveniente para que tu informe quede organizado y con un diseño atractivo. **<font color='blue'>¡Importante! La fuente de datos tiene muchos registros de tipo nulo, utilizá recursos como filtros para que no perjudiquen las visualizaciones!</font>**:

    <b>H.</b> Construir un mapa coroplético que muestre la cantidad títulos (series y movies) por país. No tomes en cuenta las colaboraciones entre varios países, sólo títulos que los que produce un único país.

    <b>I.</b> Construir un gráfico que muestre de forma descendente el top 20 de directores con más producciones. Incluir un control que permita filtrar por los tipos de títulos (Movie-TvShow).

    <b>J.</b> Construir un gráfico que muestre de forma descendente los 10 géneros de Netflix con mayor cantidad de producciones.
    
    <b>K.</b> Construir un gráfico que muestre de forma descendente el top 10 de clasificaciones por público (rating) desglosando por tipo de contenido. 

    <b>L.</b> Construir un gráfico que muestre de forma ascendente las 20 películas o series más antiguas.  
    
    <b>M.</b> Construir un gráfico que muestre de forma descendete los 15 idiomas de películas con mayor cantidad de títulos, sin contar inglés.

## Enlace al <a href="https://lookerstudio.google.com/s/kfcS_qa0Ga8">informe</a> de LookerStudio.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=ea0812e1-0d76-44d2-a032-78c433150a28' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>